---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
     - id: check-json
     - id: detect-aws-credentials
     - id: detect-private-key
     - id: trailing-whitespace
       exclude: >
           (?x)^(
               test/files/helm-template-output.yaml
           )$
     - id: check-added-large-files
       args: ['--maxkb=150']
     - id: check-byte-order-marker
     - id: check-merge-conflict
     - id: check-symlinks
     - id: end-of-file-fixer
       exclude: >
           (?x)^(
               test/files/helm-template-output.yaml
           )$
     - id: no-commit-to-branch
       args: [--branch, master]
     - id: pretty-format-json
       args: ['--autofix']
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 1.10.3
    hooks:
      - id: forbid-binary
      - id: shellcheck
        args:
          - -e
          - SC1091
          - -e
          - SC2068
          - -x
