#!/bin/sh

# Redirect output to stderr.
exec 1>&2

secrets=$(find . -name '*.secrets.yml')

if [[ $secrets ]]; then
  echo
  echo "VALIDATION ERROR:"
  echo "You may have unencrypted Secrets files."
  echo "Aborting Commit."
  echo "You should fix these:"
  echo $secrets
  echo
  exit 1
fi
