---
apiVersion: v1
kind: Service
metadata:
  name: rok8s-example
  labels:
    app: rok8s-example
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: rok8s-example
