---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: appname
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: appname
  targetCPUUtilizationPercentage: 80
