---
apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
    dns: route53
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
    # Requires https://github.com/wearemolecule/route53-kubernetes for DNS
    domainName: app.example.io

    # Uncomment for an Internal ELB
    # service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: example
    version: latest
