apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-latest

spec:
  minReadySeconds: 15
  revisionHistoryLimit: 3
  replicas: 3
  template:
    metadata:
      labels:
        app: example
        version: latest
    spec:
      volumes:
        - name: config
          configMap:
            name: example-config
        - name: secrets
          secret:
            secretName: example-secrets
      containers:
        - name: example
          # `latest` will be replaced with $CI_SHA1 by k8s-deploy
          image: alpine
          command: ["sleep","86400"]
          ports:
          - containerPort: 5000
            name: http
          volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            exec:
              command:
                - "ls"
            initialDelaySeconds: 10
