apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.name" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels.dns }}
    dns: {{ .Values.labels.dns }}
{{- end }}
{{- if .Values.nodeSelector }}
  annotations:
  {{ toYaml .Values.annotations }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "chart.name" . }}
    release: {{ .Release.Name }}
